[ejs.landing]
updateAvailableTooltip = "Actualización disponible"
usernamePlaceholder = "Usuario"
usernameEditButton = "Editar"
settingsTooltip = "Ajustes"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "DESCONOCIDO"
mojangStatus = "ESTADO DE MOJANG"
mojangStatusTooltipTitle = "Servicios"
mojangStatusNETitle = "No&nbsp;Esencial"
newsButton = "NOTICIAS"
launchButton = "JUGAR"
launchButtonPlaceholder = "&#8226; Ningún servidor seleccionado"
launchDetails = "Por favor esperá..."
newsNavigationStatus = "{currentPage} de {totalPages}"
newsErrorLoadSpan = "Buscando noticias..."
newsErrorFailedSpan = "Error al cargar noticias"
newsErrorRetryButton = "Intentar de nuevo"
newsErrorNoneSpan = "Sin noticias"

[ejs.login]
loginCancelText = "Cancelar"
loginSubheader = "Ingresá a tu cuenta"
loginEmailError = "* Valor inválido"
loginEmailPlaceholder = "CORREO O USUARIO"
loginPasswordError = "* Requerido"
loginPasswordPlaceholder = "CONTRASEÑA"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "olvidaste tu contraseña?"
loginRememberMeText = "recordarme?"
loginButtonText = "entrar"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "¿Necesitás una cuenta?"
loginPasswordDisclaimer1 = "Tu contraseña se envia directamente a Mojang AB y nunca se almacena."
loginPasswordDisclaimer2 = "{appName} no esta afiliado con Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Agregá una cuenta"
loginWithMicrosoft = "Iniciar sesión con Microsoft"
cancelButton = "Cancelar"

[ejs.overlay]
serverSelectHeader = "Servidores disponibles"
serverSelectConfirm = "Seleccionar"
serverSelectCancel = "Cancelar"
accountSelectHeader = "Seleccionar una cuenta"
accountSelectConfirm = "Seleccionar"
accountSelectCancel = "Cancelar"

[ejs.settings]
navHeaderText = "Ajustes"
navAccount = "Cuenta"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Acerca de"
navUpdates = "Actualizaciones"
navDone = "Listo"
tabAccountHeaderText = "Ajustes de cuenta"
tabAccountHeaderDesc = "Agregar nuevas cuentas o gestionar las existentes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Agregar cuenta de Microsoft"
minecraftTabHeaderText = "Ajustes de Minecraft"
minecraftTabHeaderDesc = "Opciones relacionadas con el lanzamiento del juego."
gameResolutionTitle = "Resolución del juego"
launchFullscreenTitle = "Lanzar en pantalla completa."
autoConnectTitle = "Conectarse automaticamente al servidor al iniciar."
launchDetachedTitle = "Lanzar el proceso del juego separado del launcher."
launchDetachedDesc = "Si el juego no se separa, cerrar el launcher tambien cerrará el juego."
tabModsHeaderText = "Ajustes de mods"
tabModsHeaderDesc = "Habilitar o deshabilitar mods."
switchServerButton = "Cambiar"
requiredMods = "Mods requeridos"
optionalMods = "Mods opcionales"
dropinMods = "Mods drop-in"
addMods = "Agregar mods"
dropinRefreshNote = "(F5 para refrescar)"
shaderpacks = "Shaders"
shaderpackDesc = "Habilitar o deshabilitar shaders. Tené en cuenta que los shaders solo funcionaran bien en compus medianamente potentes. Podés agregar shaders personalizados acá."
selectShaderpack = "Seleccionar shaderpack"
tabJavaHeaderText = "Ajustes de Java"
tabJavaHeaderDesc = "Gestionar la configuracion de Java (avanzado)."
memoryTitle = "Memoria"
maxRAM = "RAM máxima"
minRAM = "RAM mínima"
memoryDesc = "La RAM mínima recomendada es de 3 gigabytes. Establecer los valores mínimo y máximo al mismo valor puede reducir el lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Ejecutable de Java"
javaExecSelDialogTitle = "Seleccionar ejecutable de Java"
javaExecSelButtonText = "Elegir archivo"
javaExecDesc = "El ejecutable de Java es validado antes del lanzamiento del juego."
javaPathDesc = "El camino debe terminar con <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opciones adicionales de JVM"
jvmOptsDesc = "Opciones que se proporcionaran a la JVM al momento de la ejecución. <em>-Xms</em> y <em>-Xmx</em> no deben ser incluidas."
launcherTabHeaderText = "Ajustes del Launcher"
launcherTabHeaderDesc = "Opciones relacionadas con el launcher."
allowPrereleaseTitle = "Permitir actualizaciones previas a la version final."
allowPrereleaseDesc = "Los pre-lanzamientos incluyen nuevas caracteristicas que pueden no haber sido completamente probadas o integradas.<br>Si activás esta opción, aceptas que puedan existir errores."
dataDirectoryTitle = "Directorio de datos"
selectDataDirectory = "Seleccionar directorio de datos"
chooseFolder = "Elegir carpeta"
dataDirectoryDesc = "Todos los archivos del juego y las instalaciones locales de Java serán almacenados en el directorio de datos.<br>Las capturas de pantalla y los guardados de mundos se almacenan en la carpeta de la instancia para la configuracion correspondiente del servidor."
aboutTabHeaderText = "Acerca de"
aboutTabHeaderDesc = "Ver información y notas de la version para la version actual."
aboutTitle = "{appName}"
stableRelease = "Version estable"
versionText = "Version "
sourceGithub = "Fuente (GitHub)"
support = "Soporte"
devToolsConsole = "Consola de herramientas de desarrollador"
releaseNotes = "Notas de la version"
changelog = "Registro de cambios"
noReleaseNotes = "No hay notas de la version"
viewReleaseNotes = "Ver notas de la version en GitHub"
launcherUpdatesHeaderText = "Actualizaciones del Launcher"
launcherUpdatesHeaderDesc = "Descargar, instalar y revisar actualizaciones para el launcher."
checkForUpdates = "Buscar actualizaciones"
whatsNew = "¿Que hay nuevo?"
updateReleaseNotes = "Notas de la version de la actualización"

[ejs.waiting]
waitingText = "Esperando a Microsoft..."

[ejs.welcome]
continueButton = "Continuar"

[js.discord]
waiting = "Esperando cliente..."
state = "Servidor: {shortId}"

[js.index]
microsoftLoginTitle = "Inicio de sesión con Microsoft"
microsoftLogoutTitle = "Cierre de sesión con Microsoft"

[js.login]
login = "Iniciar sesión"
loggingIn = "Iniciando sesión"
success = "Éxito"
tryAgain = "Intentar de nuevo"

[js.login.error]
invalidValue = "* Valor inválido"
requiredValue = "* Requerido"

[js.login.error.unknown]
title = "Error desconocido durante el inicio de sesión"
desc = "Ocurrió un error desconocido. Revisá la consola para mas detalles."

[js.landing.launch]
pleaseWait = "Por favor esperá..."
failureTitle = "Error durante el lanzamiento"
failureText = "Revisá la consola (CTRL + Shift + i) para mas detalles."
okay = "Aceptar"

[js.landing.selectedAccount]
noAccountSelected = "Ninguna cuenta seleccionada"

[js.landing.selectedServer]
noSelection = "Ningún servidor seleccionado"
loading = "Cargando..."

[js.landing.serverStatus]
server = "Servidor"
offline = "Desconocido"
players = "JUGADORES"

[js.landing.systemScan]
checking = "Revisando información del sistema..."
noCompatibleJava = "No se encontró una instalación compatible de Java"
installJavaMessage = "Para lanzar Minecraft, necesitás una instalacion de Java {major} de 64 bits. ¿Querés que instalemos una copia?"
installJava = "Instalar Java"
installJavaManually = "No, quiero instalarlo manualmente"
javaDownloadPrepare = "Preparando descarga de Java..."
javaDownloadFailureTitle = "Error durante la descarga de Java"
javaDownloadFailureText = "Revisá la consola (CTRL + Shift + i) para mas detalles."
javaRequired = "Java es requerido<br>para lanzar"
javaRequiredMessage = 'Se requiere una instalacion valida de x64 Java {major} para lanzar.'
javaRequiredDismiss = "Entiendo"
javaRequiredCancel = "Volver"

[js.landing.downloadJava]
findJdkFailure = "No se encontró la distribución de Java."
javaDownloadCorruptedError = "El instalador de Java descargado tiene un hash incorrecto, el archivo puede estar corrupto."
extractingJava = "Extrayendo Java..."
javaInstalled = "¡Java instalado!"

[js.landing.dlAsync]
loadingServerInfo = "Cargando información del servidor..."
fatalError = "Error fatal"
unableToLoadDistributionIndex = "No se pudo cargar una copia del indice de distribucion."
pleaseWait = "Por favor esperá..."
errorDuringLaunchTitle = "Error durante el lanzamiento"
seeConsoleForDetails = "Revisá la consola (CTRL + Shift + i) para mas detalles."
validatingFileIntegrity = "Validando integridad de los archivos..."
errorDuringFileVerificationTitle = "Error durante la verificación de archivos"
downloadingFiles = "Descargando archivos..."
errorDuringFileDownloadTitle = "Error durante la descarga de archivos"
preparingToLaunch = "Preparando para lanzar..."
launchingGame = "Lanzando juego..."
launchWrapperNotDownloaded = "El archivo principal, LaunchWrapper, no se descargo correctamente. Como resultado, el juego no puede lanzarse.<br><br>Para solucionar este problema, apaga temporalmente tu software antivirus y volvé a lanzar el juego.<br><br>Si tenés tiempo, por favor <a href=\"https://github.com/aleshyy/AAKSLauncher/issues\">reporta el problema</a> y decinos que software antivirus usas. Nos pondremos en contacto con ellos para resolverlo."
doneEnjoyServer = "Listo. Pasala bien."
checkConsoleForDetails = "Por favor revisá la consola (CTRL + Shift + i) para mas detalles."

[js.landing.news]
checking = "Buscando noticias"

[js.landing.discord]
loading = "Cargando juego..."
joining = "En camino a PlataGang"
joined = "Sobreviviendo en PlataGang"

[js.overlay]
dismiss = "Descartar"

[js.settings.fileSelectors]
executables = "Ejecutables"
allFiles = "Todos los archivos"

[js.settings.mstfLogin]
errorTitle = "Algo salió mal"
errorMessage = "Falló la autenticación de Microsoft. Por favor intentá de nuevo."
okButton = "Aceptar"

[js.settings.mstfLogout]
errorTitle = "Algo salió mal"
errorMessage = "El cierre de sesión de Microsoft falló. Por favor, intentalo de nuevo."
okButton = "Aceptar"

[js.settings.authAccountSelect]
selectButton = "Elegir cuenta"
selectedButton = "Cuenta actual &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Advertencia<br>Esta es tu última cuenta"
lastAccountWarningMessage = "Para usar el launcher debes estar logueado en al menos una cuenta. Tenés que iniciar sesión de nuevo después.<br><br>¿Estás seguro de que querés cerrar sesión?"
confirmButton = "Confirmar"
cancelButton = "Cancelar"

[js.settings.authAccountPopulate]
username = "Usuario"
uuid = "UUID"
selectAccount = "Elegir cuenta"
selectedAccount = "Cuenta actual ✓"
logout = "Cerrar sesión"

[js.settings.dropinMods]
removeButton = "Eliminar"
deleteFailedTitle = "Falló al eliminar<br>Mod {fullName}"
deleteFailedMessage = "Asegurate de que el archivo no esté en uso y volvé a intentarlo."
failedToggleTitle = "Falló al Activar/Desactivar<br>Uno o mas mods."
okButton = "Aceptar"

[js.settings.serverListing]
mainServer = "Servidor Principal"

[js.settings.java]
selectedJava = "Seleccionado: Java {version} ({vendor})"
invalidSelection = "Selección Inválida"
requiresJava = "Requiere Java {major} x64."
availableOptions = "Opciones Disponibles para Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Beta"
stableReleaseTitle = "Estable"
releaseNotesFailed = "Falló al cargar las notas de la versión."

[js.settings.updates]
newReleaseTitle = "¡Hay una nueva versión disponible!"
newPreReleaseTitle = "¡Hay un nuevo pre-lanzamiento disponible!"
downloadingButton = "Descargando..."
downloadButton = 'Descargar desde GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Cerrá el launcher y ejecutá el dmg para actualizar.</span>'
latestVersionTitle = "Estás usando la última versión"
checkForUpdatesButton = "Buscar actualizaciones"
checkingForUpdatesButton = "Buscando actualizaciones..."

[js.settings.msftLogin]
errorTitle = "Error al iniciar sesión con Microsoft"
errorMessage = "No pudimos autenticar tu cuenta de Microsoft. Por favor, intentá de nuevo."
okButton = "Aceptar"

[js.uibinder.startup]
fatalErrorTitle = "Error fatal: No se pudo cargar el índice de distribución"
fatalErrorMessage = "No se pudo establecer una conexión con nuestros servidores para descargar el índice de distribución. No se encontraron copias locales disponibles para cargar. <br><br>El índice de distribución es un archivo esencial que proporciona la información más reciente del servidor. El launcher no puede iniciarse sin él. Asegurate de estar conectado a Internet y vuelve a lanzar la aplicación."
closeButton = "Salir"

[js.uibinder.validateAccount]
failedMessageTitle = "Falló la actualización de inicio de sesión"
failedMessage = "No pudimos actualizar el inicio de sesión de <strong>{account}</strong>. Por favor, seleccioná otra cuenta o iniciá sesión nuevamente."
failedMessageSelectAnotherAccount = "No pudimos actualizar el inicio de sesión de <strong>{account}</strong>. Por favor, iniciá sesión nuevamente."
loginButton = "Iniciar sesión"
selectAnotherAccountButton = "Elegir otra cuenta"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Buscando actualizaciones...."
installNowButton = "Instalar ahora"
checkForUpdatesButton = "Buscar actualizaciones"

[js.auth.microsoft.error]
noProfileTitle = "Error durante el inicio de sesión:<br>Perfil no configurado"
noProfileDesc = "Tu cuenta de Microsoft aún no tiene un perfil de Minecraft configurado. Si compraste el juego recientemente o lo redimiste a través de Xbox Game Pass, debes configurar tu perfil en <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si aún no has comprado el juego, también podés hacerlo en <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Error durante el inicio de sesión:<br>No hay cuenta de Xbox"
noXboxAccountDesc = "Tu cuenta de Microsoft no tiene una cuenta de Xbox asociada."
xblBannedTitle = "Error durante el inicio de sesión:<br>Xbox Live no disponible"
xblBannedDesc = "Tu cuenta de Microsoft proviene de un país donde Xbox Live no está disponible o está prohibido."
under18Title = "Error durante el inicio de sesión:<br>Aprobación parental requerida"
under18Desc = "Las cuentas de usuarios menores de 18 años deben ser añadidas a una Familia por un adulto."
unknownTitle = "Error desconocido durante el inicio de sesión"
unknownDesc = "Ocurrió un error desconocido. Por favor, consulta la consola para más detalles."


