[ejs.landing]
updateAvailableTooltip = "Actualizaci√≥n disponible"
usernamePlaceholder = "Usuario"
usernameEditButton = "Editar"
settingsTooltip = "Ajustes"
landingMessage = "¬°Bienvenid@!"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "DESCONOCIDO"
mojangStatus = "ESTADO DE MOJANG"
mojangStatusTooltipTitle = "Servicios"
mojangStatusNETitle = "No&nbsp;Esencial"
newsButton = "NOTICIAS"
launchButton = "JUGAR"
launchButtonPlaceholder = "&#8226; Ning√∫n servidor seleccionado"
launchDetails = "Por favor esper√°..."
newsNavigationStatus = "{currentPage} de {totalPages}"
newsErrorLoadSpan = "Buscando noticias..."
newsErrorFailedSpan = "Error al cargar noticias"
newsErrorRetryButton = "Intentar de nuevo"
newsErrorNoneSpan = "Sin noticias"

[ejs.login]
loginCancelText = "Cancelar"
loginSubheader = "Ingres√° a tu cuenta"
loginEmailError = "* Valor inv√°lido"
loginEmailPlaceholder = "CORREO O USUARIO"
loginPasswordError = "* Requerido"
loginPasswordPlaceholder = "CONTRASE√ëA"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "olvidaste tu contrase√±a?"
loginRememberMeText = "recordarme?"
loginButtonText = "entrar"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "¬øNecesit√°s una cuenta?"
loginPasswordDisclaimer1 = "Tu contrase√±a se envia directamente a Mojang AB y nunca se almacena."
loginPasswordDisclaimer2 = "{appName} no esta afiliado con Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Agreg√° una cuenta"
loginWithMicrosoft = "Iniciar sesi√≥n con Microsoft"
cancelButton = "Cancelar"

[ejs.overlay]
serverSelectHeader = "Servidores disponibles"
serverSelectConfirm = "Seleccionar"
serverSelectCancel = "Cancelar"
accountSelectHeader = "Seleccionar una cuenta"
accountSelectConfirm = "Seleccionar"
accountSelectCancel = "Cancelar"

[ejs.settings]
navHeaderText = "Ajustes"
navAccount = "Cuenta"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Acerca de"
navUpdates = "Actualizaciones"
navDone = "Listo"
tabAccountHeaderText = "Ajustes de cuenta"
tabAccountHeaderDesc = "Agregar nuevas cuentas o gestionar las existentes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Agregar cuenta de Microsoft"
minecraftTabHeaderText = "Ajustes de Minecraft"
minecraftTabHeaderDesc = "Opciones relacionadas con el lanzamiento del juego."
gameResolutionTitle = "Resoluci√≥n del juego"
launchFullscreenTitle = "Lanzar en pantalla completa."
autoConnectTitle = "Conectarse automaticamente al servidor al iniciar."
launchDetachedTitle = "Lanzar el proceso del juego separado del launcher."
launchDetachedDesc = "Si el juego no se separa, cerrar el launcher tambien cerrar√° el juego."
tabModsHeaderText = "Ajustes de mods"
tabModsHeaderDesc = "Habilitar o deshabilitar mods."
switchServerButton = "Cambiar"
requiredMods = "Mods requeridos"
optionalMods = "Mods opcionales"
dropinMods = "Mods drop-in"
addMods = "Agregar mods"
dropinRefreshNote = "(F5 para refrescar)"
shaderpacks = "Shaders"
shaderpackDesc = "Habilitar o deshabilitar shaders. Ten√© en cuenta que los shaders solo funcionaran bien en compus medianamente potentes. Pod√©s agregar shaders personalizados ac√°."
selectShaderpack = "Seleccionar shaders"
resourcepacks = "Resource Packs"
resourcepackDesc = "Habilitar o deshabilit√°r paquetes de recursos. Ten√© en cuenta que esto solo funciona para el paquete principal. Pod√©s agregar paquetes personalizados ac√°."
selectResourcepack = "Seleccionar resourcepack"
tabJavaHeaderText = "Ajustes de Java"
tabJavaHeaderDesc = "Gestionar la configuracion de Java (avanzado)."
memoryTitle = "Memoria"
maxRAM = "RAM m√°xima"
minRAM = "RAM m√≠nima"
memoryDesc = "La RAM m√≠nima recomendada es de 3 gigabytes. Establecer los valores m√≠nimo y m√°ximo al mismo valor puede reducir el lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Ejecutable de Java"
javaExecSelDialogTitle = "Seleccionar ejecutable de Java"
javaExecSelButtonText = "Elegir archivo"
javaExecDesc = "El ejecutable de Java es validado antes del lanzamiento del juego."
javaPathDesc = "El camino debe terminar con <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opciones adicionales de JVM"
jvmOptsDesc = "Opciones que se proporcionaran a la JVM al momento de la ejecuci√≥n. <em>-Xms</em> y <em>-Xmx</em> no deben ser incluidas."
launcherTabHeaderText = "Ajustes del Launcher"
launcherTabHeaderDesc = "Opciones relacionadas con el launcher."
allowPrereleaseTitle = "Permitir actualizaciones previas a la versi√≥n final."
allowPrereleaseDesc = "Los pre-lanzamientos incluyen nuevas caracteristicas que pueden no haber sido completamente probadas o integradas.<br>Si activ√°s esta opci√≥n, aceptas que puedan existir errores."
dataDirectoryTitle = "Directorio de datos"
selectDataDirectory = "Seleccionar directorio de datos"
chooseFolder = "Elegir carpeta"
dataDirectoryDesc = "Todos los archivos del juego y las instalaciones locales de Java ser√°n almacenados en el directorio de datos.<br>Las capturas de pantalla y los guardados de mundos se almacenan en la carpeta de la instancia para la configuracion correspondiente del servidor."
aboutTabHeaderText = "Acerca de"
aboutTabHeaderDesc = "Ver informaci√≥n y notas de la versi√≥n para la versi√≥n actual."
aboutTitle = "{appName}"
stableRelease = "Versi√≥n estable"
versionText = "Versi√≥n "
#sourceGithub = "Fuente (GitHub)"
support = "Soporte"
devToolsConsole = "Consola de herramientas de desarrollador"
releaseNotes = "Notas de la versi√≥n"
changelog = "Registro de cambios"
noReleaseNotes = "No hay notas de la versi√≥n"
viewReleaseNotes = "Ver notas de la versi√≥n en GitHub"
launcherUpdatesHeaderText = "Actualizaciones del Launcher"
launcherUpdatesHeaderDesc = "Descargar, instalar y revisar actualizaciones para el launcher."
checkForUpdates = "Buscar actualizaciones"
whatsNew = "¬øQue hay nuevo?"
updateReleaseNotes = "Notas de la versi√≥n de la actualizaci√≥n"

[ejs.waiting]
waitingText = "Esperando a Microsoft..."

[ejs.welcome]
welcomeHeader = "¬°Bienvenid@ a AAKS Launcher!"
welcomeDescription = "Instalar mods puede ser m√°s complicado que hacer un asado en plena tormenta, pero tranqui, estamos para salvarte. Vos relajate, que nosotros hacemos la magia."
welcomeDescCTA = "Est√°s a un par de clics de mandarte al server. üòé"
continueButton = "¬°Dale, vamos!"

[js.discord]
waiting = "Esperando cliente..."
state = "Servidor: {shortId}"

[js.index]
microsoftLoginTitle = "Inicio de sesi√≥n con Microsoft"
microsoftLogoutTitle = "Cierre de sesi√≥n con Microsoft"

[js.login]
login = "Iniciar sesi√≥n"
loggingIn = "Iniciando sesi√≥n"
success = "√âxito"
tryAgain = "Intentar de nuevo"

[js.login.error]
invalidValue = "* Valor inv√°lido"
requiredValue = "* Requerido"

[js.login.error.unknown]
title = "Error desconocido durante el inicio de sesi√≥n"
desc = "Ocurri√≥ un error desconocido. Revis√° la consola para mas detalles."

[js.landing.launch]
pleaseWait = "Por favor esper√°..."
failureTitle = "Error durante el lanzamiento"
failureText = "Revis√° la consola (CTRL + Shift + i) para mas detalles."
okay = "Aceptar"

[js.landing.selectedAccount]
noAccountSelected = "Ninguna cuenta seleccionada"

[js.landing.selectedServer]
noSelection = "Ning√∫n servidor seleccionado"
loading = "Cargando..."

[js.landing.serverStatus]
server = "Servidor"
offline = "Desconocido"
players = "JUGADORES"

[js.landing.systemScan]
checking = "Revisando informaci√≥n del sistema..."
noCompatibleJava = "No se encontr√≥ una instalaci√≥n compatible de Java"
installJavaMessage = "Para lanzar Minecraft, necesit√°s una instalacion de Java {major} de 64 bits. ¬øQuer√©s que instalemos una copia?"
installJava = "Instalar Java"
installJavaManually = "No, quiero instalarlo manualmente"
javaDownloadPrepare = "Preparando descarga de Java..."
javaDownloadFailureTitle = "Error durante la descarga de Java"
javaDownloadFailureText = "Revis√° la consola (CTRL + Shift + i) para mas detalles."
javaRequired = "Java es requerido<br>para lanzar"
javaRequiredMessage = 'Se requiere una instalacion valida de x64 Java {major} para lanzar.'
javaRequiredDismiss = "Entiendo"
javaRequiredCancel = "Volver"

[js.landing.downloadJava]
findJdkFailure = "No se encontr√≥ la distribuci√≥n de Java."
javaDownloadCorruptedError = "El instalador de Java descargado tiene un hash incorrecto, el archivo puede estar corrupto."
extractingJava = "Extrayendo Java..."
javaInstalled = "¬°Java instalado!"

[js.landing.dlAsync]
loadingServerInfo = "Cargando informaci√≥n del servidor..."
fatalError = "Error fatal"
unableToLoadDistributionIndex = "No se pudo cargar una copia del indice de distribucion."
pleaseWait = "Por favor esper√°..."
errorDuringLaunchTitle = "Error durante el lanzamiento"
seeConsoleForDetails = "Revis√° la consola (CTRL + Shift + i) para mas detalles."
validatingFileIntegrity = "Validando integridad de los archivos..."
errorDuringFileVerificationTitle = "Error durante la verificaci√≥n de archivos"
downloadingFiles = "Descargando archivos..."
errorDuringFileDownloadTitle = "Error durante la descarga de archivos"
preparingToLaunch = "Preparando para lanzar..."
launchingGame = "Lanzando juego..."
launchWrapperNotDownloaded = "El archivo principal, LaunchWrapper, no se descargo correctamente. Como resultado, el juego no puede lanzarse.<br><br>Para solucionar este problema, apaga temporalmente tu software antivirus y volv√© a lanzar el juego.<br><br>Si ten√©s tiempo, por favor <a href=\"https://github.com/aleshyy/AAKSLauncher/issues\">reporta el problema</a> y decinos que software antivirus usas. Nos pondremos en contacto con ellos para resolverlo."
doneEnjoyServer = "Listo. Pasala bien."
checkConsoleForDetails = "Por favor revis√° la consola (CTRL + Shift + i) para mas detalles."

[js.landing.news]
checking = "Buscando noticias"

[js.landing.discord]
loading = "Cargando juego..."
joining = "En camino a PlataGang"
joined = "Sobreviviendo en PlataGang"

[js.overlay]
dismiss = "Descartar"

[js.settings.fileSelectors]
executables = "Ejecutables"
allFiles = "Todos los archivos"

[js.settings.mstfLogin]
errorTitle = "Algo sali√≥ mal"
errorMessage = "Fall√≥ la autenticaci√≥n de Microsoft. Por favor intent√° de nuevo."
okButton = "Aceptar"

[js.settings.mstfLogout]
errorTitle = "Algo sali√≥ mal"
errorMessage = "El cierre de sesi√≥n de Microsoft fall√≥. Por favor, intentalo de nuevo."
okButton = "Aceptar"

[js.settings.authAccountSelect]
selectButton = "Elegir cuenta"
selectedButton = "Cuenta actual &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Advertencia<br>Esta es tu √∫ltima cuenta"
lastAccountWarningMessage = "Para usar el launcher debes estar logueado en al menos una cuenta. Ten√©s que iniciar sesi√≥n de nuevo despu√©s.<br><br>¬øEst√°s seguro de que quer√©s cerrar sesi√≥n?"
confirmButton = "Confirmar"
cancelButton = "Cancelar"

[js.settings.authAccountPopulate]
username = "Usuario"
uuid = "UUID"
selectAccount = "Elegir cuenta"
selectedAccount = "Cuenta actual ‚úì"
logout = "Cerrar sesi√≥n"

[js.settings.dropinMods]
removeButton = "Eliminar"
deleteFailedTitle = "Fall√≥ al eliminar<br>Mod {fullName}"
deleteFailedMessage = "Asegurate de que el archivo no est√© en uso y volv√© a intentarlo."
failedToggleTitle = "Fall√≥ al Activar/Desactivar<br>Uno o mas mods."
okButton = "Aceptar"

[js.settings.serverListing]
mainServer = "Servidor Principal"

[js.settings.java]
selectedJava = "Seleccionado: Java {version} ({vendor})"
invalidSelection = "Selecci√≥n Inv√°lida"
requiresJava = "Requiere Java {major} x64."
availableOptions = "Opciones Disponibles para Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Beta"
stableReleaseTitle = "Estable"
releaseNotesFailed = "Fall√≥ al cargar las notas de la versi√≥n."

[js.settings.updates]
newReleaseTitle = "¬°Hay una nueva versi√≥n disponible!"
newPreReleaseTitle = "¬°Hay un nuevo pre-lanzamiento disponible!"
downloadingButton = "Descargando..."
downloadButton = 'Descargar desde GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Cerr√° el launcher y ejecut√° el dmg para actualizar.</span>'
latestVersionTitle = "Est√°s usando la √∫ltima versi√≥n"
checkForUpdatesButton = "Buscar actualizaciones"
checkingForUpdatesButton = "Buscando actualizaciones..."

[js.settings.msftLogin]
errorTitle = "Error al iniciar sesi√≥n con Microsoft"
errorMessage = "No pudimos autenticar tu cuenta de Microsoft. Por favor, intent√° de nuevo."
okButton = "Aceptar"

[js.uibinder.startup]
fatalErrorTitle = "Error fatal: No se pudo cargar el √≠ndice de distribuci√≥n"
fatalErrorMessage = "No se pudo establecer una conexi√≥n con nuestros servidores para descargar el √≠ndice de distribuci√≥n. No se encontraron copias locales disponibles para cargar. <br><br>El √≠ndice de distribuci√≥n es un archivo esencial que proporciona la informaci√≥n m√°s reciente del servidor. El launcher no puede iniciarse sin √©l. Asegurate de estar conectado a Internet y vuelve a lanzar la aplicaci√≥n."
closeButton = "Salir"

[js.uibinder.validateAccount]
failedMessageTitle = "Fall√≥ la actualizaci√≥n de inicio de sesi√≥n"
failedMessage = "No pudimos actualizar el inicio de sesi√≥n de <strong>{account}</strong>. Por favor, seleccion√° otra cuenta o inici√° sesi√≥n nuevamente."
failedMessageSelectAnotherAccount = "No pudimos actualizar el inicio de sesi√≥n de <strong>{account}</strong>. Por favor, inici√° sesi√≥n nuevamente."
loginButton = "Iniciar sesi√≥n"
selectAnotherAccountButton = "Elegir otra cuenta"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Buscando actualizaciones...."
installNowButton = "Instalar ahora"
checkForUpdatesButton = "Buscar actualizaciones"

[js.auth.microsoft.error]
noProfileTitle = "Error durante el inicio de sesi√≥n:<br>Perfil no configurado"
noProfileDesc = "Tu cuenta de Microsoft a√∫n no tiene un perfil de Minecraft configurado. Si compraste el juego recientemente o lo redimiste a trav√©s de Xbox Game Pass, debes configurar tu perfil en <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si a√∫n no has comprado el juego, tambi√©n pod√©s hacerlo en <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Error durante el inicio de sesi√≥n:<br>No hay cuenta de Xbox"
noXboxAccountDesc = "Tu cuenta de Microsoft no tiene una cuenta de Xbox asociada."
xblBannedTitle = "Error durante el inicio de sesi√≥n:<br>Xbox Live no disponible"
xblBannedDesc = "Tu cuenta de Microsoft proviene de un pa√≠s donde Xbox Live no est√° disponible o est√° prohibido."
under18Title = "Error durante el inicio de sesi√≥n:<br>Aprobaci√≥n parental requerida"
under18Desc = "Las cuentas de usuarios menores de 18 a√±os deben ser a√±adidas a una Familia por un adulto."
unknownTitle = "Error desconocido durante el inicio de sesi√≥n"
unknownDesc = "Ocurri√≥ un error desconocido. Por favor, consulta la consola para m√°s detalles."


